'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Infraestructura.Repositorio.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @sqlquery varchar(max)
        '''
        '''set @sqlquery=&apos; where 1=1 &apos;
        '''
        '''IF (@id is not null and @id &lt;&gt;0)
        ''' set @sqlquery = @sqlquery + &apos; AND ID = &apos;&apos;&apos;+  @id+&apos;&apos;&apos;&apos;
        '''
        '''IF @cliente is not null and @cliente&lt;&gt;&apos;&apos;
        ''' set @sqlquery = @sqlquery + &apos; AND CLIENTE =&apos;&apos;&apos;+  @cliente+&apos;&apos;&apos;&apos;
        '''
        '''IF (@telefono &lt;&gt; null or @telefono &lt;&gt;&apos;&apos;)
        ''' set @sqlquery = @sqlquery + &apos; AND TELEFONO =&apos;&apos;&apos;+  @telefono+&apos;&apos;&apos;&apos;
        '''
        '''IF (@correo &lt;&gt; null or @correo &lt;&gt;&apos;&apos;)
        ''' set @sqlquery = @sqlquery + &apos; AND CORREO =&apos;&apos;&apos;+  @correo+&apos;&apos;&apos;&apos;
        '''
        '''exec(&apos;select* from clientes &apos; +  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property BuscarCliente() As String
            Get
                Return ResourceManager.GetString("BuscarCliente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @sqlquery varchar(max)
        '''set @sqlquery=&apos; where 1=1 &apos;
        '''
        '''IF (@id is not null and @id &lt;&gt;0)
        ''' set @sqlquery = @sqlquery + &apos; AND ID = &apos;&apos;&apos;+  @id+&apos;&apos;&apos;&apos;
        '''IF (@nombre &lt;&gt; NULL or @nombre &lt;&gt;&apos;&apos;)
        ''' set @sqlquery = @sqlquery + &apos; AND NOMBRE =&apos;&apos;&apos;+  @nombre+&apos;&apos;&apos;&apos;
        '''IF (@precio is not null and @precio &lt;&gt;0)
        ''' set @sqlquery = @sqlquery + &apos; AND PRECIO =&apos;&apos;&apos;+  @precio+&apos;&apos;&apos;&apos;
        '''IF (@categoria &lt;&gt; null or @categoria &lt;&gt;&apos;&apos;)
        ''' set @sqlquery = @sqlquery + &apos; AND CATEGORIA =&apos;&apos;&apos;+  @categoria+&apos;&apos;&apos;&apos;
        '''
        '''exec(&apos;select* from productos &apos; + @sqlq [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property BuscarProducto() As String
            Get
                Return ResourceManager.GetString("BuscarProducto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a declare @sqlquery varchar(max)
        '''
        '''set @sqlquery=&apos; where 1=1 &apos;
        '''
        '''IF (@id is not null and @id &lt;&gt;0)
        ''' set @sqlquery = @sqlquery + &apos; AND ID = &apos;&apos;&apos;+  @id+&apos;&apos;&apos;&apos;
        '''
        '''IF @cliente is not null and @cliente&lt;&gt;&apos;&apos;
        ''' set @sqlquery = @sqlquery + &apos; AND IDCLIENTE =&apos;&apos;&apos;+  @idcliente+&apos;&apos;&apos;&apos;
        '''
        '''IF (@telefono &lt;&gt; null or @telefono &lt;&gt;&apos;&apos;)
        ''' set @sqlquery = @sqlquery + &apos; AND FECHA =&apos;&apos;&apos;+  @fecha+&apos;&apos;&apos;&apos;
        '''
        '''exec(&apos;select* from ventas &apos; + @sqlquery)
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property BuscarVenta() As String
            Get
                Return ResourceManager.GetString("BuscarVenta", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
